### PR TITLE
CI: adding workflow dispatch

### PR DESCRIPTION
**Pull request by bsipocz**
CI has been disabled, this will make it easier to restart it next time.

### CODE REVIEW

**Comment by bsipocz** [comment]
Ahh, can of worms, just as expected.

**Comment by pllim** [comment]
Why is pandas trying to look for HDF5?

`ERROR:: Could not find a local HDF5 installation.`

**Comment by bsipocz** [comment]
> Why is pandas trying to look for HDF5?

your guess is as good as mine, especially since this job used to pass.

(practically, due to the setuptools issue that popped up in filter subpackages, I went through the rest of the plugins to see if they affected, too)

**Comment by pllim** [comment]
Looks like `macos-latest` might be the culprit. Maybe something else has been pulling in HDF5 but somehow that failed with OSX ARM64 + numpy 2.0 ?

**Comment by bsipocz** [comment]
Well, the issue is that `pytables` doesn't yet support ARM osx with their latest release (3.9.2 2023 Nov), so I'm certain this just won't work until their 3.9.3 is out.

I'll add some hackery to our CI for the meantime.

**Pull request merged**
